# Site settings

title: Your awesome title
email: your-email@example.com

description: >- # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.

# Formal
github_username: artlessavian

# STRICTLY INFORMAL (is this a good idea to have?)
twitter_username: artlessavian

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# exclude:
#   - vendor/ruby/

collections:
  - images

plugins:
  - jekyll-octicons