
# If you find yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Ryan Chang
email: artlessavian@gmail.com
description:
  Website for Ryan, aka ArtlessAvian.
baseurl: ""
url: "artlessavian.github.io"

repository: artlessavian/artlessavian.github.io

theme: jekyll-theme-modernist