
# If you find yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: artlessavian.github.io
email: artlessavian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Some guy who pretends to write games.
baseurl: ""
url: "artlessavian.github.io"

# twitter_username: jekyllrb
github_username:  artlessavian

date-format: "%b %-d, %Y"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-octicons

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  notable_proj_collection:
    output : true